# Generated by Django 3.1.7 on 2021-07-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(max_length=200, null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subjects.question')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
    ]
